### ISSUE TITLE
Unknown provider: sessionProvider

### ISSUE THREAD

**Issue by cedk** [openlabs/angular-tryton#30]
The example doesn't work and raise this error (when using non minified libraries):

```
 Uncaught Error: [$injector:modulerr] Failed to instantiate module myApp due to:
Error: [$injector:modulerr] Failed to instantiate module openlabs.angular-tryton due to:
Error: [$injector:unpr] Unknown provider: sessionProvider
http://errors.angularjs.org/1.2.28/$injector/unpr?p0=sessionProvider
    at VALIDITY_STATE_PROPERTY (http://localhost:8000/example/bower_components/angular/angular.js:78:12)
    at http://localhost:8000/example/bower_components/angular/angular.js:3801:19
    at getService (http://localhost:8000/example/bower_components/angular/angular.js:3929:39)
    at Object.invoke (http://localhost:8000/example/bower_components/angular/angular.js:3956:13)
    at http://localhost:8000/example/bower_components/angular/angular.js:3884:37
    at forEach (http://localhost:8000/example/bower_components/angular/angular.js:325:18)
    at loadModules (http://localhost:8000/example/bower_components/angular/angular.js:3871:5)
    at http://localhost:8000/example/bower_components/angular/angular.js:3878:40
    at forEach (http://localhost:8000/example/bower_components/angular/angular.js:325:18)
    at loadModules (http://localhost:8000/example/bower_components/angular/angular.js:3871:5)
http://errors.angularjs.org/1.2.28/$injector/modulerr?p0=openlabs.angular-t…host%3A8000%2Fexample%2Fbower_components%2Fangular%2Fangular.js%3A3871%3A5)
    at VALIDITY_STATE_PROPERTY (http://localhost:8000/example/bower_components/angular/angular.js:78:12)
    at http://localhost:8000/example/bower_components/angular/angular.js:3905:15
    at forEach (http://localhost:8000/example/bower_components/angular/angular.js:325:18)
    at loadModules (http://localhost:8000/example/bower_components/angular/angular.js:3871:5)
    at http://localhost:8000/example/bower_components/angular/angular.js:3878:40
    at forEach (http://localhost:8000/example/bower_components/angular/angular.js:325:18)
    at loadModules (http://localhost:8000/example/bower_components/angular/angular.js:3871:5)
    at createInjector (http://localhost:8000/example/bower_components/angular/angular.js:3811:11)
    at doBootstrap (http://localhost:8000/example/bower_components/angular/angular.js:1444:20)
    at bootstrap (http://localhost:8000/example/bower_components/angular/angular.js:1459:12)
http://errors.angularjs.org/1.2.28/$injector/modulerr?p0=myApp&p1=Error%3A%…ost%3A8000%2Fexample%2Fbower_components%2Fangular%2Fangular.js%3A1459%3A12)
```

**Comment by GauravButola** [comment]
It does seem like there was an issue in the example app. The newer version of angular-tryton depends on Angular `>1.3.0`; but the example app was still using an old version.

This should be fixed now. Thanks for reporting the issue @cedk .
